### ISSUE TITLE
ApiClient does not respect custom HTTP client timeout

### ISSUE THREAD

**Issue by al416** [jellyfin/jellyfin-sdk-kotlin#260]
**Describe the bug**

I am setting the timeout to 60 seconds in the following manner:

    private const val HTTP_CLIENT_TIMEOUT_IN_MS = 60000L
    
    @Singleton
    @Provides
    internal fun providesKtorClient(jellyfin: Jellyfin): KtorClient {
        val clientOptions = HttpClientOptions(followRedirects = true, timeout = HTTP_CLIENT_TIMEOUT_IN_MS)
        return jellyfin.createApi(baseUrl = null, httpClientOptions = clientOptions)
    }

However I have noticed that some requests time out after 6-10 seconds rather than 60 seconds. 

**Actual result**
This is what the timeout log looks like:
Socket timeout has expired [url=https://somedummyurl.com/Users/a8888-cca3-4c0c-8668-a05fd9cb0b9f/Items/Latest?limit=10&groupItems=true, socket_timeout=unknown] ms

Notice the socket_timeout is unknown.

**Expected result**
Request will time out after custom timeout period (60 seconds in this case).

**Comment by nielsvanvelzen** [comment]
Right now the timeout option only sets the "connection timeout" for the underlying http client. It does not set the request and socket timeouts. That's why you got this exception. 

My current idea is to add all 3 values to the HttpClientOptions class so you can change all of the timeouts separately. Would this work for you?

**Comment by al416** [comment]
That would be perfect!
