### ISSUE TITLE
Add RecommendedServerIssue for connection problems

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-sdk-kotlin#351]
Right now connection issues are emitted as MissingSystemInfo, with the throwable pointing to an ApiClientException with a cause containing the actual exception emitted from OkHttp.

**This can be made better/easier.**

I'd suggest creating a new issue type "NoConnection". It should contain the throwable and an enum explaining what went wrong with the connection: bad SSL, no internet etc.

**Comment by alialiusefi** [comment]
Hi! Is this issue still actual? I would like to work on this if you dont mind

**Comment by nielsvanvelzen** [comment]
Yes. We have a lot of issue reports for our clients caused by SSL issues. Right no we don't detect those in the SDK which isn't helpful. I'd like to have a single RecommendedServerIssue for all SSL related issues with more detail in it's body (e.g. the exception that caused it, maybe an enum with the type of SSL error).

The NoConnection one is also still nice to have.

**Comment by alialiusefi** [comment]
Ok. I will look into the code and familarize myself with the api client.

**Comment by alialiusefi** [comment]
Hi! What do you think of naming the RecommentedServerIssue implementation for SSL Errors as BadConnection? IMO, NoConnection is a bit misleading.

BadConnection implies we reached the server but there was configuration issues (e.g SSL configuration error).
NoConnection implies we didn't reach the server at all.

Regardless of the naming -> I will try to map ssl errors thrown by OkHttp due to SSL in a genric way and add that to the new implementation class.

**Comment by nielsvanvelzen** [comment]
Yes they should be separate, one for SSL related issues and one for no connection. Maybe name it something like "UnsupportedSSL"? Since it's not necessarily a bad connection.

**Comment by alialiusefi** [comment]
Hi! Sorry for the delay, I created a pull request with required feature. I'm still thinking on how to approach testing this...
