### ISSUE TITLE
[Feature Request] include link in the source to the corresponding jf api website page for a given model

### ISSUE THREAD

**Issue by mueslimak3r** [jellyfin/jellyfin-sdk-kotlin#354]
It's sometimes unclear where to find more info about a class or field using https://api.jellyfin.org or https://jellyfin.org/docs/plugin-api or by googling.
Is it possible for the generator to automatically add a url in the source as a comment?
example:
```
/*
** https://jellyfin.org/docs/plugin-api/MediaBrowser.Model.Dto.MediaSourceInfo.html
*/

public class MediaSourceInfo
{
...
```

afaik the generator doesn't use the plugin-api, but I used it in this example since I can't find MediaSourceInfo on api.jellyfin.org

**Comment by nielsvanvelzen** [comment]
The documentation that is generated in the SDK is based on that from the server, so if you want a comment to be more descriptive it should be changed in the server and the generator will pick it up. It's not really possible to link to the server class files because the OpenAPI spec doesn't really have the information (doesn't contain the namespaces for example) so we can't map it to the .cs files in the server. Linking to api.jellyfin.org could be possible but that page is generated from the exact same specification so it wouldn't give you much more info.
